"""Added urole for users and Events model.

Revision ID: f52600bff009
Revises: c1c2c536245b
Create Date: 2021-10-26 15:15:33.930169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52600bff009'
down_revision = 'c1c2c536245b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_cutoff', sa.DateTime(), nullable=True),
    sa.Column('event_start', sa.DateTime(), nullable=True),
    sa.Column('event_end', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.String(length=140), nullable=True),
    sa.Column('client_restriction', sa.String(length=140), nullable=True),
    sa.Column('bike_restriction', sa.String(length=140), nullable=True),
    sa.Column('more_info', sa.String(length=140), nullable=True),
    sa.Column('event_name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_end'), 'events', ['event_end'], unique=False)
    op.create_index(op.f('ix_events_event_start'), 'events', ['event_start'], unique=False)
    op.create_index(op.f('ix_events_pickup_cutoff'), 'events', ['pickup_cutoff'], unique=False)
    op.add_column('user', sa.Column('urole', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'urole')
    op.drop_index(op.f('ix_events_pickup_cutoff'), table_name='events')
    op.drop_index(op.f('ix_events_event_start'), table_name='events')
    op.drop_index(op.f('ix_events_event_end'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
